--REVERSE A NUMERICAL NUMBER 
--MOD(number,10) will pop the last number of array

DECLARE
ACTUAL_NUMBER NUMBER:=110298;
REVERSE_NUMBER NUMBER:=0;
BEGIN
    WHILE ACTUAL_NUMBER>0 LOOP
    REVERSE_NUMBER:=(REVERSE_NUMBER*10)+MOD(ACTUAL_NUMBER,10);
    ACTUAL_NUMBER:=TRUNC(ACTUAL_NUMBER/10);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE(REVERSE_NUMBER);
    END;