DECLARE
INPUT_A NUMBER:=10;
BINARY_SRTING VARCHAR2(100):='';
BEGIN
WHILE INPUT_A!=0 LOOP
BINARY_SRTING:=BINARY_SRTING||MOD(INPUT_A,2);
INPUT_A:=TRUNC(INPUT_A/2);
END LOOP;
DBMS_OUTPUT.PUT_LINE(BINARY_SRTING);
END;