DECLARE
TYPE ASS_ARRAY IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
V_ARRAY ASS_ARRAY:=ASS_ARRAY(10, 20, 30, 5, 15);
V_MIN NUMBER:=V_ARRAY(1);
LEN NUMBER:=V_ARRAY.COUNT;
BEGIN
FOR i in 1..LEN LOOP
IF(V_ARRAY(i)<V_MIN) THEN V_MIN:=V_ARRAY(i);
END IF;
END LOOP;
DBMS_OUTPUT.PUT_LINE(V_MIN);
END;