DECLARE
INPUT_NUMBER NUMBER:=39;
IS_PRIME BOOLEAN:=TRUE;
BEGIN
IF INPUT_NUMBER<2
THEN IS_PRIME:= FALSE;
ELSE
WHILE i <=SQRT(INPUT_NUMBER) LOOP
IF(MOD(INPUT_NUMBER/i))=0 THEN 
IS_PRIME:=FALSE;
EXIT;
END IF;
i=i+1;
END LOOP;
END IF;
IF IS_PRIME THEN
DBMS_OUTPUT.PUT_LINE(INPUT_NUMBER||' IS PRIME');
ELSE 
DBMS_OUTPUT.PUT_LINE(INPUT_NUMBER||' IS NOT PRIME');
END IF;
END;