DECLARE
INPUT_NUMBER  NUMBER:=4;
FACTORIAL NUMBER:=1;
BEGIN
FOR i in REVERSE 1..INPUT_NUMBER LOOP
FACTORIAL:=FACTORIAL*i;
END LOOP;
DBMS_OUTPUT.PUT_LINE('FACTORIAL OF '||INPUT_NUMBER||' IS '||FACTORIAL);
END;