DECLARE INPUT_STRING NVARCHAR2(30):='avinash';
STRING_COUNT NUMBER:=0;
BEGIN
FOR i in 1..LENGTH(INPUT_STRING) LOOP
IF(SUBSTR(UPPER(INPUT_STRING),i,1) IN ('A','E','I','O','U'))
THEN STRING_COUNT:=STRING_COUNT+1;
END IF;
END LOOP;
DBMS_OUTPUT.PUT_LINE(STRING_COUNT);
    END;