DECLARE
V_NUM NUMBER:=10;
SUM_NATURAL NUMBER;
BEGIN
SUM_NATURAL:=(V_NUM*(V_NUM+1))/2;
DBMS_OUTPUT.PUT_LINE(SUM_NATURAL);
END;

--SECOND APPROACH
DECLARE
V_NUM NUMBER:=10;
SUM_NATURAL NUMBER:=0;
BEGIN
FOR i in 1..V_NUM LOOP
SUM_NATURAL:=SUM_NATURAL+i;
END LOOP;
DBMS_OUTPUT.PUT_LINE(SUM_NATURAL);
END;
