DECLARE
V_DEAPRTMENT_ID EMPLOYEES.DEPARTMENT_ID%TYPE:=20;
BEGIN
    DELETE FROM EMPLOYEES WHERE DEPARTMENT_ID=V_DEAPRTMENT_ID;
    COMMIT;
    END;
-- TO TEST
    SELECT * FROM EMPLOYEES WHERE EMPLOYEES.DEPARTMENT_ID=20;
