DECLARE
INPUT_NUMBER NUMBER:=021198;
SUM_NUMBER NUMBER:=0;
BEGIN
While INPUT_NUMBER!=0 LOOP
SUM_NUMBER:=SUM_NUMBER+MOD(INPUT_NUMBER,10);
INPUT_NUMBER:=TRUNC(INPUT_NUMBER/10);
END LOOP;
DBMS_OUTPUT.PUT_LINE('SUM IS '||SUM_NUMBER);
END;