DECLARE
INPUT_NUMBER NUMBER:=17;
BEGIN
IF SQRT(INPUT_NUMBER)=TRUNC(SQRT(INPUT_NUMBER)) THEN
DBMS_OUTPUT.PUT_LINE(INPUT_NUMBER||' IS SQUARE ROOT NUMBER');
ELSE DBMS_OUTPUT.PUT_LINE(INPUT_NUMBER||' IS NOT SQUARE ROOT NUMBER');
END IF;
END;