DECLARE
TYPE V_ARRAY IS TABLE OF NUMBER;
INPUT_ARRAY V_ARRAY:=V_ARRAY(10,20,20,30,40,40,40);
COUNT_MODE NUMBER:=0;
MAX_COUNT_MODE NUMBER:=0;
MODE_NUMBER NUMBER:=0;
BEGIN

FOR i IN INPUT_ARRAY.FIRST..INPUT_ARRAY.LAST LOOP
COUNT_MODE:=0;
FOR j IN INPUT_ARRAY.FIRST..INPUT_ARRAY.LAST LOOP

IF(INPUT_ARRAY(i)=INPUT_ARRAY(j)) THEN
COUNT_MODE:=COUNT_MODE+1;
END IF;
END LOOP;

IF(COUNT_MODE>MAX_COUNT_MODE) THEN
MAX_COUNT_MODE:=COUNT_MODE;
MODE_NUMBER:=INPUT_ARRAY(i);
END IF;
END LOOP;
DBMS_OUTPUT.PUT_LINE('MODE IS '||MODE_NUMBER);
END;