DECLARE
TYPE ASS_ARRAY IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
V_ARRAY ASS_ARRAY:=ASS_ARRAY(10, 20, 30, 5, 15);
SUM_ARRAY NUMBER:=0;
LEN NUMBER:=V_ARRAY.COUNT;
BEGIN
FOR i in 1..LEN LOOP
SUM_ARRAY:=SUM_ARRAY+V_ARRAY(i);
END LOOP;
SUM_ARRAY:=SUM_ARRAY/V_ARRAY.COUNT;
DBMS_OUTPUT.PUT_LINE(SUM_ARRAY);
END;