DECLARE CURSOR RANK_SALARY IS
    SELECT EMPLOYEE_ID,SALARY,DENSE_RANK()OVER(ORDER BY SALARY DESC) AS SALARY_RANK FROM EMPLOYEES;
V_ID EMPLOYEES.EMPLOYEE_ID%TYPE;
V_SALARY EMPLOYEES.SALARY%TYPE;
V_RANK NUMBER(10);
BEGIN
    OPEN RANK_SALARY;
    LOOP
    FETCH RANK_SALARY INTO  V_ID,V_SALARY,V_RANK;
    EXIT WHEN RANK_SALARY%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE('RANKING OF '||V_SALARY || 'in Employee'||V_ID||' is '|| V_RANK);
    END LOOP;
    CLOSE RANK_SALARY;
    END;