DECLARE CURSOR TARGET IS
SELECT SALESPERSON_NAME,MIN(SALES_DATE) AS REACHED FROM
(SELECT SALESPERSON_NAME,
SUM(SALES_AMOUNT) OVER(PARTITION BY SALESPERSON_NAME ORDER BY SALES_DATE) AS Total_Sales ,
SALES_DATE FROM SALES)
WHERE Total_Sales>100000
GROUP BY SALESPERSON_NAME;
BEGIN
    FOR rec in TARGET LOOP
    DBMS_OUTPUT.PUT_LINE(rec.SALESPERSON_NAME|| ' ' || rec.REACHED);
    END LOOP;
    END;