CREATE OR REPLACE FUNCTION AVG_SALARY(DEPT_ID EMPLOYEES.DEPARTMENT_ID%TYPE)
RETURN NUMBER IS
SAL_AVG EMPLOYEES.SALARY%TYPE;
BEGIN
    SELECT AVG(SALARY) INTO SAL_AVG FROM EMPLOYEES WHERE DEPARTMENT_ID=DEPT_ID;
DBMS_OUTPUT.PUT_LINE('Average Salary of DEPT '||DEPT_ID||' is '||SAL_AVG);
    RETURN SAL_AVG;
    END;

-- TO TEST
DECLARE
A NUMBER(10);
    BEGIN
        A:=AVG_SALARY(10);
        END;

