CREATE OR REPLACE PROCEDURE EVENODD(V_INPUT_A NUMBER) IS
INPUT_A NUMBER:=V_INPUT_A;
EVENODD BOOLEAN:=TRUE;
BEGIN
IF(V_INPUT_A MOD 2)!=0 THEN EVENODD:=FALSE;
END IF;
IF EVENODD THEN 
DBMS_OUTPUT.PUT_LINE(V_INPUT_A||' IS EVEN');
ELSE
DBMS_OUTPUT.PUT_LINE(V_INPUT_A||' IS ODD');
END IF;
END;
--TEST
BEGIN
    EVENODD(81);
END;