CREATE OR REPLACE PROCEDURE INSERT_EMP
(
V_EMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE,
V_FIRST_NAME EMPLOYEES.FIRST_NAME%TYPE,
V_SALARY EMPLOYEES.SALARY%TYPE,
V_DEPARTMENT_ID EMPLOYEES.DEPARTMENT_ID%TYPE
) IS
BEGIN
INSERT INTO EMPLOYEES VALUES(V_EMPLOYEE_ID,V_FIRST_NAME,V_SALARY,V_DEPARTMENT_ID);
COMMIT;
    END;