CREATE OR REPLACE PROCEDURE PALINDROME(INPUT_STRING IN VARCHAR2) IS
REVERSE_STRING VARCHAR2(20);
BEGIN
    FOR i in REVERSE 1..LENGTH(INPUT_STRING) LOOP
REVERSE_STRING:=REVERSE_STRING||SUBSTR(INPUT_STRING,i,1);
END LOOP;
IF(REVERSE_STRING=INPUT_STRING)
THEN DBMS_OUTPUT.PUT_LINE('THE STRING '||INPUT_STRING||' IS PALINDROME');
ELSE DBMS_OUTPUT.PUT_LINE('THE STRING '||INPUT_STRING||' IS NOT PALINDROME');
END IF;
END;
--TO TEST
BEGIN 
    PALINDROME('DADDY');
END;