CREATE OR REPLACE PROCEDURE LCM(V_INPUT_A NUMBER,V_INPUT_B NUMBER) IS
INPUT_A NUMBER:=V_INPUT_A;
INPUT_B NUMBER:=V_INPUT_B;
GCD NUMBER;
LCM  NUMBER;
BEGIN
WHILE INPUT_B!=0 LOOP
GCD:= INPUT_A MOD INPUT_B;
INPUT_A:=INPUT_B;
INPUT_B:=GCD;
END LOOP;
LCM:=(V_INPUT_A*V_INPUT_B)/INPUT_A;
DBMS_OUTPUT.PUT_LINE('LCM IS '||LCM);
END;

-- To Test
BEGIN
    LCM(12,15);
END;