CREATE OR REPLACE PROCEDURE GCD(V_INPUT_A NUMBER,V_INPUT_B NUMBER) IS
INPUT_A NUMBER:=V_INPUT_A;
INPUT_B NUMBER:=V_INPUT_B;
GCD NUMBER;
BEGIN
WHILE INPUT_B!=0 LOOP
GCD:= INPUT_A MOD INPUT_B;
INPUT_A:=INPUT_B;
INPUT_B:=GCD;
END LOOP;
DBMS_OUTPUT.PUT_LINE('GCD IS '||INPUT_A);
END;

-- To Test
BEGIN
    GCD(18,48);
END;