CREATE OR REPLACE TRIGGER SALARY_CAP
BEFORE INSERT ON EMPLOYEES
FOR EACH ROW
BEGIN
    IF:NEW.SALARY>20000 THEN
    DBMS_OUTPUT.PUT_LINE('Salary should not exceed $20000');
    RAISE_APPLICATION_ERROR(-20001,'Salary should not exceed $20,000');
    END IF;
    END;

--To TEST
    INSERT INTO EMPLOYEES VALUES(8,'Deeshu',90000,20);